/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductRouteImport } from './routes/product'
import { Route as OrderRouteImport } from './routes/order'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as CategoryRouteImport } from './routes/category'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryAddRouteImport } from './routes/category.add'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryAddRoute = CategoryAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => CategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/category': typeof CategoryRouteWithChildren
  '/customer': typeof CustomerRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/product': typeof ProductRoute
  '/profile': typeof ProfileRoute
  '/category/add': typeof CategoryAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/category': typeof CategoryRouteWithChildren
  '/customer': typeof CustomerRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/product': typeof ProductRoute
  '/profile': typeof ProfileRoute
  '/category/add': typeof CategoryAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/category': typeof CategoryRouteWithChildren
  '/customer': typeof CustomerRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/product': typeof ProductRoute
  '/profile': typeof ProfileRoute
  '/category/add': typeof CategoryAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/category'
    | '/customer'
    | '/login'
    | '/order'
    | '/product'
    | '/profile'
    | '/category/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/category'
    | '/customer'
    | '/login'
    | '/order'
    | '/product'
    | '/profile'
    | '/category/add'
  id:
    | '__root__'
    | '/'
    | '/category'
    | '/customer'
    | '/login'
    | '/order'
    | '/product'
    | '/profile'
    | '/category/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryRoute: typeof CategoryRouteWithChildren
  CustomerRoute: typeof CustomerRoute
  LoginRoute: typeof LoginRoute
  OrderRoute: typeof OrderRoute
  ProductRoute: typeof ProductRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/add': {
      id: '/category/add'
      path: '/add'
      fullPath: '/category/add'
      preLoaderRoute: typeof CategoryAddRouteImport
      parentRoute: typeof CategoryRoute
    }
  }
}

interface CategoryRouteChildren {
  CategoryAddRoute: typeof CategoryAddRoute
}

const CategoryRouteChildren: CategoryRouteChildren = {
  CategoryAddRoute: CategoryAddRoute,
}

const CategoryRouteWithChildren = CategoryRoute._addFileChildren(
  CategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryRoute: CategoryRouteWithChildren,
  CustomerRoute: CustomerRoute,
  LoginRoute: LoginRoute,
  OrderRoute: OrderRoute,
  ProductRoute: ProductRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
